services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dupla_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  api:
    build: ./app
    container_name: duppla-financial-documents
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      # Use the service name `db` as host so the container connects to the DB service
      DATEBASE_URL: "postgresql://postgres:postgres@db:5432/dupla_db"
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data: